services:
  db:
    image: postgres:14.10
    restart: always
    environment:
      - POSTGRES_USER=tattle
      - POSTGRES_PASSWORD=weak_password
      - POSTGRES_DB=uli_community_dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - ~/data/uli_comm_dev/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

  db_gui:
    image: adminer
    restart: always
    ports:
      - 8080:8080
